server:
  port: 2325
#  servlet:
#    context-path: /springboot_mybatis
#默认访问public下面的页面。controller跳转时默认跳转到templates下面的页面

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#配置视图，默认是返回templates文件夹下面的页面
#  mvc:
#    view:
#      suffix: .html
#      prefix: /

  thymeleaf:
    cache: false
#  security:
#    user:
#      name:
#      password:
#      roles:

# 定位模板的目录


mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:com/mapping/*Mapper.xml

#不能以大写字母开头,程序启动会报错
#变量名与值之间有空格
myprops:
  name: 小明
  age: 13
  arrayProps: 1,2,3,4,5
  listProp1:
    - names: abc
      value: abcValue
    - names: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2
